
var YaneuraOu = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(YaneuraOu) {
  YaneuraOu = YaneuraOu || {};


function e(){l.buffer!=m&&q(l.buffer);return aa}function y(){l.buffer!=m&&q(l.buffer);return ba}function z(){l.buffer!=m&&q(l.buffer);return ca}function A(){l.buffer!=m&&q(l.buffer);return da}function ea(){l.buffer!=m&&q(l.buffer);return fa}null;var B;B||(B=typeof YaneuraOu !== 'undefined' ? YaneuraOu : {});var ha,ja;B.ready=new Promise(function(a,b){ha=a;ja=b});B.Xa||(B.Xa=0);B.Xa++;
(function(a){function b(n,v,p){var r=new XMLHttpRequest;r.open("GET",n,!0);r.responseType="arraybuffer";r.onprogress=function(w){var h=v;w.total&&(h=w.total);if(w.loaded){r.oa?B.za[n].loaded=w.loaded:(r.oa=!0,B.za||(B.za={}),B.za[n]={loaded:w.loaded,total:h});var t=h=w=0,x;for(x in B.za){var C=B.za[x];w+=C.total;h+=C.loaded;t++}w=Math.ceil(w*B.Xa/t);B.setStatus&&B.setStatus("Downloading data... ("+h+"/"+w+")")}else!B.za&&B.setStatus&&B.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
n);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(n){console.error("package error:",n)}function d(){function n(w,h,t){this.start=w;this.end=h;this.audio=t}function v(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.Kb=w;w=a.files;for(var h=
0;h<w.length;++h)n.prototype.oa[w[h].filename].onload();B.removeRunDependency("datafile_yaneuraou.data")}B.FS_createPath("/","eval",!0,!0);n.prototype={oa:{},open:function(w,h){this.name=h;this.oa[h]=this;B.addRunDependency("fp "+this.name)},onload:function(){this.Ya(this.Kb.subarray(this.start,this.end))},Ya:function(w){B.FS_createDataFile(this.name,null,w,!0,!0,!0);B.removeRunDependency("fp "+this.name);this.oa[this.name]=null}};for(var p=a.files,r=0;r<p.length;++r)(new n(p[r].start,p[r].end,p[r].audio)).open("GET",
p[r].filename);B.addRunDependency("datafile_yaneuraou.data");B.yb||(B.yb={});B.yb["yaneuraou.data"]={wc:!1};u?(v(u),u=null):k=v}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof B.locateFilePackage||B.locateFile||(B.locateFile=B.locateFilePackage,D("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=B.locateFile?B.locateFile("yaneuraou.data",""):"yaneuraou.data",g=a.remote_package_size,k=null,u=B.getPreloadedPackage?B.getPreloadedPackage(f,g):null;u||b(f,g,function(n){k?(k(n),k=null):u=n},c);B.calledRun?d():(B.preRun||(B.preRun=[]),B.preRun.push(d))})({files:[{filename:"/eval/nn.bin",
start:0,end:893917,audio:0}],remote_package_size:893917,package_uuid:"4e8664c0-710e-4347-8416-314852b601fa"});
(function(){function a(){var g=d.shift();if(!b&&void 0!==g){if("quit"===g)return B.terminate();var k=B.ccall("usi_command","number",["string"],[g]);k&&d.unshift(g);f=k?2*f:1;setTimeout(a,f)}}var b=!1,c=[];B.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var k=0;k<c.length;k++)c[k](g)})};B.addMessageListener=function(g){c.push(g)};B.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};B.terminate=function(){b=!0;E.Db()};var d=[],f=1;B.postMessage=function(g){d.push(g)};
B.postRun=function(){B.postMessage=function(g){d.push(g);1===d.length&&a()};a()}})();var ka={},F;for(F in B)B.hasOwnProperty(F)&&(ka[F]=B[F]);var la=[],ma="./this.program";function na(a,b){throw b;}var oa=!1,I=!1,pa=!1;oa="object"===typeof window;I="function"===typeof importScripts;pa="object"===typeof process&&"object"===typeof process.lc&&"string"===typeof process.lc.node;var J=B.ENVIRONMENT_IS_PTHREAD||!1,K="";function qa(a){return B.locateFile?B.locateFile(a,K):K+a}var ra,sa;
if(oa||I)I?K=self.location.href:"undefined"!==typeof document&&document.currentScript&&(K=document.currentScript.src),_scriptDir&&(K=_scriptDir),0!==K.indexOf("blob:")?K=K.substr(0,K.lastIndexOf("/")+1):K="",ra=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},I&&(sa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ta=B.print||console.log.bind(console),D=B.printErr||console.warn.bind(console);
for(F in ka)ka.hasOwnProperty(F)&&(B[F]=ka[F]);ka=null;B.arguments&&(la=B.arguments);B.thisProgram&&(ma=B.thisProgram);B.quit&&(na=B.quit);var ua,va;B.wasmBinary&&(va=B.wasmBinary);var noExitRuntime=B.noExitRuntime||!0;"object"!==typeof WebAssembly&&L("no native wasm support detected");var l,wa,xa=!1;function ya(a,b){a||L("Assertion failed: "+b)}function za(a){var b=B["_"+a];ya(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Aa(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function M(a){return a?Aa(y(),a,void 0):""}
function Ba(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var u=a.charCodeAt(++g);k=65536+((k&1023)<<10)|u&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Da(a){var b=Ca(a)+1,c=Ea(b);Ba(a,e(),c,b);return c}function Fa(a,b){e().set(a,b)}var m,aa,ba,Ga,ca,da,fa;J&&(m=B.buffer);
function q(a){m=a;B.HEAP8=aa=new Int8Array(a);B.HEAP16=Ga=new Int16Array(a);B.HEAP32=ca=new Int32Array(a);B.HEAPU8=ba=new Uint8Array(a);B.HEAPU16=new Uint16Array(a);B.HEAPU32=da=new Uint32Array(a);B.HEAPF32=new Float32Array(a);B.HEAPF64=fa=new Float64Array(a)}var Ha=B.INITIAL_MEMORY||71303168;
if(J)l=B.wasmMemory,m=B.buffer;else if(B.wasmMemory)l=B.wasmMemory;else if(l=new WebAssembly.Memory({initial:Ha/65536,maximum:32768,shared:!0}),!(l.buffer instanceof SharedArrayBuffer))throw D("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),pa&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");l&&(m=l.buffer);Ha=m.byteLength;q(m);var Ia,Ja=[],Ka=[],La=[],Ma=[];function Na(){J||(B.noFSInit||Oa||(Oa=!0,Pa(),B.stdin=B.stdin,B.stdout=B.stdout,B.stderr=B.stderr,B.stdin?N("/dev","stdin",B.stdin):Qa("/dev/tty","/dev/stdin"),B.stdout?N("/dev","stdout",null,B.stdout):Qa("/dev/tty","/dev/stdout"),B.stderr?N("/dev","stderr",null,B.stderr):Qa("/dev/tty1","/dev/stderr"),Ra("/dev/stdin",0),Ra("/dev/stdout",1),Ra("/dev/stderr",1)),Sa(Ka))}
function Ta(){var a=B.preRun.shift();Ja.unshift(a)}var Ua=0,Va=null,Wa=null;function Xa(){ya(!J,"addRunDependency cannot be used in a pthread worker");Ua++;B.monitorRunDependencies&&B.monitorRunDependencies(Ua)}function Ya(){Ua--;B.monitorRunDependencies&&B.monitorRunDependencies(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}B.preloadedImages={};B.preloadedAudios={};
function L(a){if(B.onAbort)B.onAbort(a);J&&console.error("Pthread aborting at "+Error().stack);D(a);xa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ja(a);throw a;}function Za(){return O.startsWith("data:application/octet-stream;base64,")}var O="yaneuraou.wasm";Za()||(O=qa(O));function $a(){var a=O;try{if(a==O&&va)return new Uint8Array(va);if(sa)return sa(a);throw"both async and sync fetching of the wasm failed";}catch(b){L(b)}}
function ab(){return va||!oa&&!I||"function"!==typeof fetch?Promise.resolve().then(function(){return $a()}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return $a()})}var bb,cb,eb={28692:function(){throw"Canceled!";},28710:function(a,b){setTimeout(function(){db(a,b)},0)}};
function Sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(B);else{var c=b.xc;"number"===typeof c?void 0===b.Ea?Ia.get(c)():Ia.get(c)(b.Ea):c(void 0===b.Ea?null:b.Ea)}}}
function fb(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(z(),gb>>2),d=0;if(c==a&&Atomics.compareExchange(z(),gb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(z(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}B._emscripten_futex_wake=fb;
function hb(a){if(J)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=E.qa[a];b&&(z()[a+12>>2]=0,E.Qa(b.worker))}
var E={sa:[],wa:[],fb:[],Nb:function(){for(var a=0;1>a;++a)E.hb()},Ob:function(){for(var a=P(228),b=0;57>b;++b)A()[a/4+b]=0;z()[a+12>>2]=a;b=a+152;z()[b>>2]=b;var c=P(512);for(b=0;128>b;++b)A()[c/4+b]=0;Atomics.store(A(),a+100>>2,c);Atomics.store(A(),a+40>>2,a);ib(a,!I,1);jb(a)},Pb:function(){E.receiveObjectTransfer=E.Vb;E.threadInit=E.dc;E.threadCancel=E.bc;E.threadExit=E.cc;E.setExitStatus=E.$b},qa:{},Eb:[],Xb:function(){for(;0<E.Eb.length;)E.Eb.pop()();J&&Q()&&kb()},Cb:function(a,b){Atomics.store(A(),
a+56>>2,1);Atomics.store(A(),a+60>>2,0);E.Xb();Atomics.store(A(),a+4>>2,b);Atomics.store(A(),a+0>>2,1);fb(a+0,2147483647);ib(0,0,0)},$b:function(){},cc:function(a){var b=Q();b&&(E.Cb(b,a),J&&postMessage({cmd:"exit"}))},bc:function(){E.Cb(Q(),-1);postMessage({cmd:"cancelDone"})},Db:function(){for(var a in E.qa){var b=E.qa[a];b&&b.worker&&E.Qa(b.worker)}E.qa={};for(a=0;a<E.sa.length;++a){var c=E.sa[a];c.terminate()}E.sa=[];for(a=0;a<E.wa.length;++a)c=E.wa[a],b=c.na,E.$a(b),c.terminate();E.wa=[]},$a:function(a){if(a){if(a.ra){var b=
z()[a.ra+100>>2];z()[a.ra+100>>2]=0;lb(b);lb(a.ra)}a.ra=0;a.Wa&&a.ya&&lb(a.ya);a.ya=0;a.worker&&(a.worker.na=null)}},Qa:function(a){E.Yb(function(){delete E.qa[a.na.ra];E.sa.push(a);E.wa.splice(E.wa.indexOf(a),1);E.$a(a.na);a.na=void 0})},Yb:function(a){z()[mb>>2]=0;try{a()}finally{z()[mb>>2]=1}},Vb:function(){},dc:function(){for(var a in E.fb)E.fb[a]()},sb:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.na&&(E.Ib=a.na.ra);if(d.targetThread&&d.targetThread!=Q()){var g=E.qa[d.Lc];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)nb();else if("spawnThread"===f)ob(c.data);else if("cleanupThread"===f)hb(d.thread);else if("killThread"===f){c=d.thread;if(J)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";z()[c+12>>2]=0;c=E.qa[c];c.worker.terminate();
E.$a(c);E.wa.splice(E.wa.indexOf(c.worker),1);c.worker.na=void 0}else if("cancelThread"===f){c=d.thread;if(J)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";E.qa[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.Ia&&(a.Ia(),delete a.Ia);else if("print"===f)ta("Thread "+d.threadId+": "+d.text);else if("printErr"===f)D("Thread "+d.threadId+": "+d.text);else if("alert"===
f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.na&&Atomics.load(A(),a.na.ra+64>>2)&&E.Qa(a);else if("exitProcess"===f)try{pb(d.returnCode)}catch(k){if(k instanceof qb)return;throw k;}else"cancelDone"===f?E.Qa(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):D("worker sent an unknown command "+f));E.Ib=void 0};a.onerror=function(c){D("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:B.mainScriptUrlOrBlob||
_scriptDir,wasmMemory:l,wasmModule:wa})},hb:function(){var a=qa("yaneuraou.worker.js");E.sa.push(new Worker(a))},Lb:function(){0==E.sa.length&&(E.hb(),E.sb(E.sa[0]));return E.sa.pop()},qc:function(a){for(a=performance.now()+a;performance.now()<a;);}};B.establishStackSpace=function(a,b){rb(a,b);sb(a)};B.invokeEntryPoint=function(a,b){return Ia.get(a)(b)};var tb=0;function ub(){return noExitRuntime||0<tb}B.keepRuntimeAlive=ub;var vb;
vb=J?function(){return performance.now()-B.__performance_now_clock_drift}:function(){return performance.now()};function wb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function R(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=wb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function xb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function yb(a){if("/"===a)return"/";a=R(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function zb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){L("randomDevice")}}
function Ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=wb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Bb=[];function Cb(a,b){Bb[a]={input:[],ja:[],Ba:b};Db(a,Eb)}
var Eb={open:function(a){var b=Bb[a.node.Pa];if(!b)throw new S(43);a.ia=b;a.seekable=!1},close:function(a){a.ia.Ba.flush(a.ia)},flush:function(a){a.ia.Ba.flush(a.ia)},read:function(a,b,c,d){if(!a.ia||!a.ia.Ba.qb)throw new S(60);for(var f=0,g=0;g<d;g++){try{var k=a.ia.Ba.qb(a.ia)}catch(u){throw new S(29);}if(void 0===k&&0===f)throw new S(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.ia||!a.ia.Ba.cb)throw new S(60);try{for(var f=
0;f<d;f++)a.ia.Ba.cb(a.ia,b[c+f])}catch(g){throw new S(29);}d&&(a.node.timestamp=Date.now());return f}},Gb={qb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Fb(b,!0)}return a.input.shift()},cb:function(a,b){null===b||10===b?(ta(Aa(a.ja,0)),a.ja=[]):0!=b&&a.ja.push(b)},flush:function(a){a.ja&&0<a.ja.length&&
(ta(Aa(a.ja,0)),a.ja=[])}},Hb={cb:function(a,b){null===b||10===b?(D(Aa(a.ja,0)),a.ja=[]):0!=b&&a.ja.push(b)},flush:function(a){a.ja&&0<a.ja.length&&(D(Aa(a.ja,0)),a.ja=[])}},T={pa:null,ta:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.pa||(T.pa={dir:{node:{va:T.fa.va,la:T.fa.la,Fa:T.fa.Fa,Na:T.fa.Na,Ab:T.fa.Ab,Va:T.fa.Va,Bb:T.fa.Bb,zb:T.fa.zb,Ra:T.fa.Ra},stream:{xa:T.ga.xa}},file:{node:{va:T.fa.va,la:T.fa.la},
stream:{xa:T.ga.xa,read:T.ga.read,write:T.ga.write,gb:T.ga.gb,ub:T.ga.ub,wb:T.ga.wb}},link:{node:{va:T.fa.va,la:T.fa.la,Ha:T.fa.Ha},stream:{}},jb:{node:{va:T.fa.va,la:T.fa.la},stream:Ib}});c=Jb(a,b,c,d);16384===(c.mode&61440)?(c.fa=T.pa.dir.node,c.ga=T.pa.dir.stream,c.ea={}):32768===(c.mode&61440)?(c.fa=T.pa.file.node,c.ga=T.pa.file.stream,c.ha=0,c.ea=null):40960===(c.mode&61440)?(c.fa=T.pa.link.node,c.ga=T.pa.link.stream):8192===(c.mode&61440)&&(c.fa=T.pa.jb.node,c.ga=T.pa.jb.stream);c.timestamp=
Date.now();a&&(a.ea[b]=c,a.timestamp=c.timestamp);return c},yc:function(a){return a.ea?a.ea.subarray?a.ea.subarray(0,a.ha):new Uint8Array(a.ea):new Uint8Array(0)},nb:function(a,b){var c=a.ea?a.ea.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ea,a.ea=new Uint8Array(b),0<a.ha&&a.ea.set(c.subarray(0,a.ha),0))},Wb:function(a,b){if(a.ha!=b)if(0==b)a.ea=null,a.ha=0;else{var c=a.ea;a.ea=new Uint8Array(b);c&&a.ea.set(c.subarray(0,Math.min(b,a.ha)));a.ha=b}},fa:{va:function(a){var b=
{};b.uc=8192===(a.mode&61440)?a.id:1;b.Cc=a.id;b.mode=a.mode;b.Gc=1;b.uid=0;b.zc=0;b.Pa=a.Pa;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ha:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.oc=new Date(a.timestamp);b.Ec=new Date(a.timestamp);b.tc=new Date(a.timestamp);b.Hb=4096;b.pc=Math.ceil(b.size/b.Hb);return b},la:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.Wb(a,b.size)},Fa:function(){throw Kb[44];
},Na:function(a,b,c,d){return T.createNode(a,b,c,d)},Ab:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Lb(b,c)}catch(g){}if(d)for(var f in d.ea)throw new S(55);}delete a.parent.ea[a.name];a.parent.timestamp=Date.now();a.name=c;b.ea[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Va:function(a,b){delete a.ea[b];a.timestamp=Date.now()},Bb:function(a,b){var c=Lb(a,b),d;for(d in c.ea)throw new S(55);delete a.ea[b];a.timestamp=Date.now()},zb:function(a){var b=[".",".."],c;for(c in a.ea)a.ea.hasOwnProperty(c)&&
b.push(c);return b},Ra:function(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},Ha:function(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},ga:{read:function(a,b,c,d,f){var g=a.node.ea;if(f>=a.node.ha)return 0;a=Math.min(a.node.ha-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===e().buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ea||a.ea.subarray)){if(g)return a.ea=
b.subarray(c,c+d),a.ha=d;if(0===a.ha&&0===f)return a.ea=b.slice(c,c+d),a.ha=d;if(f+d<=a.ha)return a.ea.set(b.subarray(c,c+d),f),d}T.nb(a,f+d);if(a.ea.subarray&&b.subarray)a.ea.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.ea[f+g]=b[c+g];a.ha=Math.max(a.ha,f+d);return d},xa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ha);if(0>b)throw new S(28);return b},gb:function(a,b,c){T.nb(a.node,b+c);a.node.ha=Math.max(a.node.ha,b+c)},ub:function(a,b,c,d,f,g){if(0!==b)throw new S(28);
if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.ea;if(g&2||a.buffer!==m){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=65536*Math.ceil(c/65536);for(b=P(g);c<g;)e()[b+c++]=0;c=b;if(!c)throw new S(48);e().set(a,c)}else d=!1,c=a.byteOffset;return{Jc:c,mc:d}},wb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new S(43);if(f&2)return 0;T.ga.write(a,b,0,d,c,!1);return 0}}},Mb=null,Nb={},Ob=[],Pb=1,U=null,Qb=!0,V={},S=null,Kb={};
function W(a,b){a=Ab("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ob:!0,eb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.eb)throw new S(32);a=wb(a.split("/").filter(function(k){return!!k}),!1);var f=Mb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Lb(f,a[d]);c=R(c+"/"+a[d]);f.Ga&&(!g||g&&b.ob)&&(f=f.Ga.root);if(!g||b.Za)for(g=0;40960===(f.mode&61440);)if(f=Rb(c),c=Ab(xb(c),f),f=W(c,{eb:b.eb}).node,40<g++)throw new S(32);}return{path:c,node:f}}
function Sb(a){for(var b;;){if(a===a.parent)return a=a.ta.vb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length}function Lb(a,b){var c;if(c=(c=Ub(a,"x"))?c:a.fa.Fa?0:2)throw new S(c,a);for(c=U[Tb(a.id,b)];c;c=c.Aa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.fa.Fa(a,b)}function Jb(a,b,c,d){a=new Vb(a,b,c,d);b=Tb(a.parent.id,a.name);a.Aa=U[b];return U[b]=a}
var Wb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Xb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ub(a,b){if(Qb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Yb(a,b){try{return Lb(a,b),20}catch(c){}return Ub(a,"wx")}function Zb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Ob[a])return a;throw new S(33);}
function $b(a,b){ac||(ac=function(){},ac.prototype={});var c=new ac,d;for(d in a)c[d]=a[d];a=c;b=Zb(b);a.ua=b;return Ob[b]=a}var Ib={open:function(a){a.ga=Nb[a.node.Pa].ga;a.ga.open&&a.ga.open(a)},xa:function(){throw new S(70);}};function Db(a,b){Nb[a]={ga:b}}
function bc(a,b){var c="/"===b,d=!b;if(c&&Mb)throw new S(10);if(!c&&!d){var f=W(b,{ob:!1});b=f.path;f=f.node;if(f.Ga)throw new S(10);if(16384!==(f.mode&61440))throw new S(54);}b={type:a,Hc:{},vb:b,Ub:[]};a=a.ta(b);a.ta=b;b.root=a;c?Mb=a:f&&(f.Ga=b,f.ta&&f.ta.Ub.push(b))}function cc(a,b,c){var d=W(a,{parent:!0}).node;a=yb(a);if(!a||"."===a||".."===a)throw new S(28);var f=Yb(d,a);if(f)throw new S(f);if(!d.fa.Na)throw new S(63);return d.fa.Na(d,a,b,c)}function X(a){return cc(a,16895,0)}
function dc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return cc(a,b|8192,c)}function Qa(a,b){if(!Ab(a))throw new S(44);var c=W(b,{parent:!0}).node;if(!c)throw new S(44);b=yb(b);var d=Yb(c,b);if(d)throw new S(d);if(!c.fa.Ra)throw new S(63);c.fa.Ra(c,b,a)}
function ec(a){var b=W(a,{parent:!0}).node,c=yb(a),d=Lb(b,c);a:{try{var f=Lb(b,c)}catch(k){f=k.ma;break a}var g=Ub(b,"wx");f=g?g:16384===(f.mode&61440)?31:0}if(f)throw new S(f);if(!b.fa.Va)throw new S(63);if(d.Ga)throw new S(10);try{V.willDeletePath&&V.willDeletePath(a)}catch(k){D("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.fa.Va(b,c);b=Tb(d.parent.id,d.name);if(U[b]===d)U[b]=d.Aa;else for(b=U[b];b;){if(b.Aa===d){b.Aa=d.Aa;break}b=b.Aa}try{if(V.onDeletePath)V.onDeletePath(a)}catch(k){D("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Rb(a){a=W(a).node;if(!a)throw new S(44);if(!a.fa.Ha)throw new S(28);return Ab(Sb(a.parent),a.fa.Ha(a))}function fc(a,b){a="string"===typeof a?W(a,{Za:!0}).node:a;if(!a.fa.la)throw new S(63);a.fa.la(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ra(a,b,c,d){if(""===a)throw new S(44);if("string"===typeof b){var f=Wb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=R(a);try{g=W(a,{Za:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new S(20);}else g=cc(a,c,0),f=!0;if(!g)throw new S(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new S(54);if(!f&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Xb(b)||b&512)?31:Ub(g,Xb(b)):44))throw new S(c);if(b&512){c=g;c="string"===typeof c?W(c,{Za:!0}).node:c;if(!c.fa.la)throw new S(63);if(16384===(c.mode&61440))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(f=Ub(c,"w"))throw new S(f);c.fa.la(c,{size:0,timestamp:Date.now()})}b&=-131713;d=$b({node:g,path:Sb(g),flags:b,seekable:!0,position:0,ga:g.ga,kc:[],error:!1},d);d.ga.open&&d.ga.open(d);!B.logReadFiles||b&1||(gc||(gc={}),a in gc||(gc[a]=1,D("FS.trackingDelegate error on read file: "+
a)));try{V.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),V.onOpenFile(a,g))}catch(k){D("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function hc(a){if(null===a.ua)throw new S(8);a.ab&&(a.ab=null);try{a.ga.close&&a.ga.close(a)}catch(b){throw b;}finally{Ob[a.ua]=null}a.ua=null}
function ic(a,b,c){if(null===a.ua)throw new S(8);if(!a.seekable||!a.ga.xa)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.ga.xa(a,b,c);a.kc=[]}
function jc(a,b,c,d,f,g){if(0>d||0>f)throw new S(28);if(null===a.ua)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(16384===(a.node.mode&61440))throw new S(31);if(!a.ga.write)throw new S(28);a.seekable&&a.flags&1024&&ic(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new S(70);b=a.ga.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&V.onWriteToFile)V.onWriteToFile(a.path)}catch(u){D("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
u.message)}return b}function Pa(){S||(S=function(a,b){this.node=b;this.Zb=function(c){this.ma=c};this.Zb(a);this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(function(a){Kb[a]=new S(a);Kb[a].stack="<generic error, no stack>"}))}var Oa;function kc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function lc(a,b){a="string"===typeof a?a:Sb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=R(a+"/"+c);try{X(d)}catch(f){}a=d}}return d}
function mc(a,b,c,d){a=R(("string"===typeof a?a:Sb(a))+"/"+b);c=kc(c,d);return cc(a,(void 0!==c?c:438)&4095|32768,0)}function nc(a,b,c,d,f,g){a=b?R(("string"===typeof a?a:Sb(a))+"/"+b):a;d=kc(d,f);f=cc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}fc(f,d|146);a=Ra(f,577);jc(a,c,0,c.length,0,g);hc(a);fc(f,d)}return f}
function N(a,b,c,d){a=R(("string"===typeof a?a:Sb(a))+"/"+b);b=kc(!!c,!!d);N.tb||(N.tb=64);var f=N.tb++<<8|0;Db(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,u,n){for(var v=0,p=0;p<n;p++){try{var r=c()}catch(w){throw new S(29);}if(void 0===r&&0===v)throw new S(6);if(null===r||void 0===r)break;v++;k[u+p]=r}v&&(g.node.timestamp=Date.now());return v},write:function(g,k,u,n){for(var v=0;v<n;v++)try{d(k[u+v])}catch(p){throw new S(29);}n&&(g.node.timestamp=
Date.now());return v}});return dc(a,b,f)}function oc(a){if(!(a.Rb||a.Sb||a.link||a.ea)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ra)try{a.ea=Fb(ra(a.url),!0),a.ha=a.ea.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function pc(a,b,c,d,f){function g(){this.bb=!1;this.oa=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.kb;return this.rb(p/this.kb|0)[r]}};g.prototype.Ya=function(p){this.rb=p};g.prototype.ib=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),w,h=(w=p.getResponseHeader("Accept-Ranges"))&&"bytes"===w;p=
(w=p.getResponseHeader("Content-Encoding"))&&"gzip"===w;var t=1048576;h||(t=r);var x=this;x.Ya(function(C){var H=C*t,ia=(C+1)*t-1;ia=Math.min(ia,r-1);if("undefined"===typeof x.oa[C]){var ed=x.oa;if(H>ia)throw Error("invalid range ("+H+", "+ia+") or no bytes requested!");if(ia>r-1)throw Error("only "+r+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",c,!1);r!==t&&G.setRequestHeader("Range","bytes="+H+"-"+ia);"undefined"!=typeof Uint8Array&&(G.responseType="arraybuffer");
G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);H=void 0!==G.response?new Uint8Array(G.response||[]):Fb(G.responseText||"",!0);ed[C]=H}if("undefined"===typeof x.oa[C])throw Error("doXHR failed!");return x.oa[C]});if(p||!r)t=r=1,t=r=this.rb(0).length,ta("LazyFiles on gzip forces download of the whole file when length is accessed");this.Gb=r;this.Fb=t;this.bb=
!0};if("undefined"!==typeof XMLHttpRequest){if(!I)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.bb||this.ib();return this.Gb}},kb:{get:function(){this.bb||this.ib();return this.Fb}}});var u=void 0}else u=c,k=void 0;var n=mc(a,b,d,f);k?n.ea=k:u&&(n.ea=null,n.url=u);Object.defineProperties(n,{ha:{get:function(){return this.ea.length}}});var v={};Object.keys(n.ga).forEach(function(p){var r=
n.ga[p];v[p]=function(){oc(n);return r.apply(null,arguments)}});v.read=function(p,r,w,h,t){oc(n);p=p.node.ea;if(t>=p.length)return 0;h=Math.min(p.length-t,h);if(p.slice)for(var x=0;x<h;x++)r[w+x]=p[t+x];else for(x=0;x<h;x++)r[w+x]=p.get(t+x);return h};n.ga=v;return n}
function qc(a,b,c,d,f,g,k,u,n,v){function p(h){function t(C){v&&v();u||nc(a,b,C,d,f,n);g&&g();Ya(w)}var x=!1;B.preloadPlugins.forEach(function(C){!x&&C.canHandle(r)&&(C.handle(h,r,t,function(){k&&k();Ya(w)}),x=!0)});x||t(h)}rc.Bc();var r=b?Ab(R(a+"/"+b)):a,w="cp "+r;Xa(w);"string"==typeof c?rc.nc(c,function(h){p(h)},k):p(c)}var Y={},ac,gc,sc=void 0;function tc(){sc+=4;return z()[sc-4>>2]}function uc(a){a=Ob[a];if(!a)throw new S(8);return a}
function vc(a,b,c){if(J)return Z(2,1,a,b,c);sc=c;try{var d=uc(a);switch(b){case 0:var f=tc();return 0>f?-28:Ra(d.path,d.flags,0,f).ua;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=tc(),d.flags|=f,0;case 12:return f=tc(),l.buffer!=m&&q(l.buffer),Ga[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return z()[wc()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof Y&&g instanceof S||L(g),-g.ma}}
function xc(a,b){if(J)return Z(3,1,a,b);try{if(0===b)return-28;if(b<Ca("/")+1)return-68;Ba("/",y(),a,b);return a}catch(c){return"undefined"!==typeof Y&&c instanceof S||L(c),-c.ma}}
function yc(a,b,c){if(J)return Z(4,1,a,b,c);sc=c;try{var d=uc(a);switch(b){case 21509:case 21505:return d.ia?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.ia?0:-59;case 21519:if(!d.ia)return-59;var f=tc();return z()[f>>2]=0;case 21520:return d.ia?-28:-59;case 21531:a=f=tc();if(!d.ga.Qb)throw new S(59);return d.ga.Qb(d,b,a);case 21523:return d.ia?0:-59;case 21524:return d.ia?0:-59;default:L("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Y&&g instanceof
S||L(g),-g.ma}}function zc(a,b,c){if(J)return Z(5,1,a,b,c);sc=c;try{var d=M(a),f=c?tc():0;return Ra(d,b,f).ua}catch(g){return"undefined"!==typeof Y&&g instanceof S||L(g),-g.ma}}var Ac=[];
function Bc(){I||(ua||(ua={}),ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,D("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function Cc(a,b,c){if(0>=a||a>e().length||a&1)return-28;if(oa){if(Atomics.load(z(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(z(),gb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(z(),gb>>2,0),-73;d=Atomics.exchange(z(),gb>>2,0);if(0==d)break;nb();if(Atomics.load(z(),a>>2)!=b)return-6;Atomics.exchange(z(),gb>>2,a)}return 0}a=Atomics.wait(z(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function Z(a,b){for(var c=arguments.length-2,d=Dc(),f=Ea(8*c),g=f>>3,k=0;k<c;k++){var u=arguments[2+k];ea()[g+k]=u}c=Ec(a,c,f,b);sb(d);return c}var Fc=[],Gc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Hc(a){a=2<a?M(a):a;return Gc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ic(a,b,c){var d=Hc(a);if(!d)return-4;d.Ma&&(z()[d.Ma>>2]=b,z()[d.Ma+4>>2]=c);if(d.xb||!d.sc)d.xb&&(d=d.xb),a=!1,d.La&&d.La.Ka&&(a=d.La.Ka.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.La.Ka.viewport(0,0,b,c);else{if(d.Ma){d=z()[d.Ma+8>>2];a=a?M(a):"";var f=Dc(),g=Ea(12),k=0;if(a){k=Ca(a)+1;var u=P(k);Ba(a,y(),u,k);k=u}z()[g>>2]=k;z()[g+4>>2]=b;z()[g+8>>2]=c;Jc(0,d,657457152,0,k,g);sb(f);return 1}return-4}return 0}
function Kc(a,b,c){return J?Z(6,1,a,b,c):Ic(a,b,c)}function Lc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function Mc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Nc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Oc(a,b){a.pb||(a.pb=a.getContext,a.getContext=function(d,f){f=a.pb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Pc(c,b):0}function Pc(a,b){var c=P(8);z()[c+4>>2]=Q();var d={Ac:c,attributes:b,version:b.Tb,Ka:a};a.canvas&&(a.canvas.La=d);("undefined"===typeof b.mb||b.mb)&&Qc(d);return c}
function Qc(a){a||(a=Rc);if(!a.Mb){a.Mb=!0;var b=a.Ka;Lc(b);Mc(b);Nc(b);b.vc=b.getExtension("EXT_disjoint_timer_query");b.Fc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Rc,Sc=["default","low-power","high-performance"],Tc={};
function Uc(){if(!Vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ma||"./this.program"},b;for(b in Tc)a[b]=Tc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Vc=c}return Vc}var Vc;
function Wc(a,b){if(J)return Z(7,1,a,b);try{var c=0;Uc().forEach(function(d,f){var g=b+c;f=z()[a+4*f>>2]=g;for(g=0;g<d.length;++g)e()[f++>>0]=d.charCodeAt(g);e()[f>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Y&&d instanceof S||L(d),d.ma}}function Xc(a,b){if(J)return Z(8,1,a,b);try{var c=Uc();z()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});z()[b>>2]=d;return 0}catch(f){return"undefined"!==typeof Y&&f instanceof S||L(f),f.ma}}
function Yc(a){if(J)return Z(9,1,a);try{var b=uc(a);hc(b);return 0}catch(c){return"undefined"!==typeof Y&&c instanceof S||L(c),c.ma}}
function Zc(a,b,c,d){if(J)return Z(10,1,a,b,c,d);try{a:{for(var f=uc(a),g=a=0;g<c;g++){var k=z()[b+8*g>>2],u=z()[b+(8*g+4)>>2],n=f,v=e(),p=k,r=u,w=void 0;if(0>r||0>w)throw new S(28);if(null===n.ua)throw new S(8);if(1===(n.flags&2097155))throw new S(8);if(16384===(n.node.mode&61440))throw new S(31);if(!n.ga.read)throw new S(28);var h="undefined"!==typeof w;if(!h)w=n.position;else if(!n.seekable)throw new S(70);var t=n.ga.read(n,v,p,r,w);h||(n.position+=t);var x=t;if(0>x){var C=-1;break a}a+=x;if(x<
u)break}C=a}z()[d>>2]=C;return 0}catch(H){return"undefined"!==typeof Y&&H instanceof S||L(H),H.ma}}
function $c(a,b,c,d,f){if(J)return Z(11,1,a,b,c,d,f);try{var g=uc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ic(g,a,d);cb=[g.position>>>0,(bb=g.position,1<=+Math.abs(bb)?0<bb?(Math.min(+Math.floor(bb/4294967296),4294967295)|0)>>>0:~~+Math.ceil((bb-+(~~bb>>>0))/4294967296)>>>0:0)];z()[f>>2]=cb[0];z()[f+4>>2]=cb[1];g.ab&&0===a&&0===d&&(g.ab=null);return 0}catch(k){return"undefined"!==typeof Y&&k instanceof S||L(k),k.ma}}
function ad(a,b,c,d){if(J)return Z(12,1,a,b,c,d);try{a:{for(var f=uc(a),g=a=0;g<c;g++){var k=z()[b+8*g>>2],u=z()[b+(8*g+4)>>2],n=jc(f,e(),k,u,void 0);if(0>n){var v=-1;break a}a+=n}v=a}z()[d>>2]=v;return 0}catch(p){return"undefined"!==typeof Y&&p instanceof S||L(p),p.ma}}
function ob(a){if(J)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=E.Lb();if(!b)return 6;if(void 0!==b.na)throw"Internal error!";if(!a.Oa)throw"Internal error, no pthread ptr!";E.wa.push(b);for(var c=P(512),d=0;128>d;++d)z()[c+4*d>>2]=0;var f=a.ya+a.Ca;d=E.qa[a.Oa]={worker:b,ya:a.ya,Ca:a.Ca,Wa:a.Wa,ra:a.Oa};var g=d.ra>>2;Atomics.store(A(),g+16,a.lb);Atomics.store(A(),g+25,c);Atomics.store(A(),g+10,d.ra);Atomics.store(A(),g+20,a.Ca);Atomics.store(A(),
g+19,f);Atomics.store(A(),g+26,a.Ca);Atomics.store(A(),g+28,f);Atomics.store(A(),g+29,a.lb);c=bd()+40;Atomics.store(A(),g+43,c);b.na=d;var k={cmd:"run",start_routine:a.ac,arg:a.Ea,threadInfoStruct:a.Oa,stackBase:a.ya,stackSize:a.Ca};b.Ia=function(){k.time=performance.now();b.postMessage(k,a.jc)};b.loaded&&(b.Ia(),delete b.Ia);return 0}
function cd(a,b){if(!a)return D("pthread_join attempted on a null thread pointer!"),71;if(J&&Q()==a)return D("PThread "+a+" is attempting to join to itself!"),16;if(!J&&dd()==a)return D("Main thread "+a+" is attempting to join to itself!"),16;if(z()[a+12>>2]!==a)return D("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(A(),a+64>>2))return D("Attempted to join thread "+a+", which was already detached!"),28;for(Bc();;){var c=
Atomics.load(A(),a+0>>2);if(1==c)return c=Atomics.load(A(),a+4>>2),b&&(z()[b>>2]=c),Atomics.store(A(),a+64>>2,1),J?postMessage({cmd:"cleanupThread",thread:a}):hb(a),0;if(J){var d=Q();if(d&&!Atomics.load(A(),d+56>>2)&&2==Atomics.load(A(),d+0>>2))throw"Canceled!";}J||nb();Cc(a+0,c,J?100:1)}}function fd(a){return 0===a%4&&(0!==a%100||0===a%400)}function gd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var hd=[31,29,31,30,31,30,31,31,30,31,30,31],jd=[31,28,31,30,31,30,31,31,30,31,30,31];
function kd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(fd(a.getFullYear())?hd:jd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function ld(a,b,c,d){function f(h,t,x){for(h="number"===typeof h?h.toString():h||"";h.length<t;)h=x[0]+h;return h}function g(h,t){return f(h,t,"0")}function k(h,t){function x(H){return 0>H?-1:0<H?1:0}var C;0===(C=x(h.getFullYear()-t.getFullYear()))&&0===(C=x(h.getMonth()-t.getMonth()))&&(C=x(h.getDate()-t.getDate()));return C}function u(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=kd(new Date(h.ka+1900,0,1),h.Ua);var t=new Date(h.getFullYear()+1,0,4),x=u(new Date(h.getFullYear(),0,4));t=u(t);return 0>=k(x,h)?0>=k(t,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var v=z()[d+40>>2];d={hc:z()[d>>2],fc:z()[d+4>>2],Sa:z()[d+8>>2],Ja:z()[d+12>>2],Da:z()[d+16>>2],ka:z()[d+20>>2],Ta:z()[d+24>>2],Ua:z()[d+28>>2],Mc:z()[d+
32>>2],ec:z()[d+36>>2],ic:v?M(v):""};c=M(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in v)c=c.replace(new RegExp(p,"g"),v[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");v={"%a":function(h){return r[h.Ta].substring(0,3)},"%A":function(h){return r[h.Ta]},"%b":function(h){return w[h.Da].substring(0,3)},"%B":function(h){return w[h.Da]},"%C":function(h){return g((h.ka+1900)/100|0,2)},"%d":function(h){return g(h.Ja,2)},"%e":function(h){return f(h.Ja,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return g(h.Sa,
2)},"%I":function(h){h=h.Sa;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Ja+gd(fd(h.ka+1900)?hd:jd,h.Da-1),3)},"%m":function(h){return g(h.Da+1,2)},"%M":function(h){return g(h.fc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Sa&&12>h.Sa?"AM":"PM"},"%S":function(h){return g(h.hc,2)},"%t":function(){return"\t"},"%u":function(h){return h.Ta||7},"%U":function(h){var t=new Date(h.ka+1900,0,1),x=0===t.getDay()?t:kd(t,7-t.getDay());h=new Date(h.ka+1900,h.Da,h.Ja);return 0>
k(x,h)?g(Math.ceil((31-x.getDate()+(gd(fd(h.getFullYear())?hd:jd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(x,t)?"01":"00"},"%V":function(h){var t=new Date(h.ka+1901,0,4),x=u(new Date(h.ka+1900,0,4));t=u(t);var C=kd(new Date(h.ka+1900,0,1),h.Ua);return 0>k(C,x)?"53":0>=k(t,C)?"01":g(Math.ceil((x.getFullYear()<h.ka+1900?h.Ua+32-x.getDate():h.Ua+1-x.getDate())/7),2)},"%w":function(h){return h.Ta},"%W":function(h){var t=new Date(h.ka,0,1),x=1===t.getDay()?t:kd(t,0===t.getDay()?1:7-t.getDay()+1);h=
new Date(h.ka+1900,h.Da,h.Ja);return 0>k(x,h)?g(Math.ceil((31-x.getDate()+(gd(fd(h.getFullYear())?hd:jd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(x,t)?"01":"00"},"%y":function(h){return(h.ka+1900).toString().substring(2)},"%Y":function(h){return h.ka+1900},"%z":function(h){h=h.ec;var t=0<=h;h=Math.abs(h)/60;return(t?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.ic},"%%":function(){return"%"}};for(p in v)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),v[p](d)));p=Fb(c,
!1);if(p.length>b)return 0;Fa(p,a);return p.length-1}J||E.Nb();function Vb(a,b,c,d){a||(a=this);this.parent=a;this.ta=a.ta;this.Ga=null;this.id=Pb++;this.name=b;this.mode=c;this.fa={};this.ga={};this.Pa=d}
Object.defineProperties(Vb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Sb:{get:function(){return 16384===(this.mode&61440)}},Rb:{get:function(){return 8192===(this.mode&61440)}}});Pa();U=Array(4096);bc(T,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");Db(259,{read:function(){return 0},write:function(b,c,d,f){return f}});dc("/dev/null",259);Cb(1280,Gb);Cb(1536,Hb);dc("/dev/tty",1280);dc("/dev/tty1",1536);var a=zb();N("/dev","random",a);N("/dev","urandom",a);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");bc({ta:function(){var b=Jb(a,"fd",16895,73);b.fa={Fa:function(c,d){var f=Ob[+d];if(!f)throw new S(8);c={parent:null,ta:{vb:"fake"},fa:{Ha:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var rc;B.FS_createPath=lc;B.FS_createDataFile=nc;B.FS_createPreloadedFile=qc;B.FS_createLazyFile=pc;B.FS_createDevice=N;B.FS_unlink=ec;var md=[null,function(a,b){if(J)return Z(1,1,a,b)},vc,xc,yc,zc,Kc,Wc,Xc,Yc,Zc,$c,ad];
function Fb(a,b){var c=Array(Ca(a)+1);a=Ba(a,c,0,c.length);b&&(c.length=a);return c}
var pd={c:function(a,b,c,d){L("Assertion failed: "+M(a)+", at: "+[b?M(b):"unknown filename",c,d?M(d):"unknown function"])},i:vc,q:xc,o:yc,p:zc,F:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(J)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=E.qa[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){L()},v:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=vb();else return z()[wc()>>2]=28,-1;z()[b>>2]=a/
1E3|0;z()[b+4>>2]=a%1E3*1E6|0;return 0},m:function(a,b,c){Ac.length=0;var d;for(c>>=2;d=y()[b++];)(d=105>d)&&c&1&&c++,Ac.push(d?ea()[c++>>1]:z()[c]),++c;return eb[a].apply(null,Ac)},A:Bc,g:function(){},e:Cc,f:fb,d:vb,t:function(a,b,c){y().copyWithin(a,b,b+c)},B:function(a,b,c){Fc.length=b;c>>=3;for(var d=0;d<b;d++)Fc[d]=ea()[c+d];return(0>a?eb[-a-1]:md[a]).apply(null,Fc)},u:function(a){var b=y().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{l.grow(Math.min(2147483648,d)-m.byteLength+65535>>>16);q(l.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},C:function(a,b,c){return Hc(a)?Ic(a,b,c):Kc(a,b,c)},l:function(){},E:function(a,b){b>>=2;var c=z()[b+6];b={alpha:!!z()[b],depth:!!z()[b+1],stencil:!!z()[b+2],antialias:!!z()[b+3],premultipliedAlpha:!!z()[b+4],preserveDrawingBuffer:!!z()[b+5],powerPreference:Sc[c],failIfMajorPerformanceCaveat:!!z()[b+7],Tb:z()[b+8],Dc:z()[b+
9],mb:z()[b+10],Jb:z()[b+11],Ic:z()[b+12],Kc:z()[b+13]};a=Hc(a);return!a||b.Jb?0:Oc(a,b)},x:Wc,y:Xc,D:function(a){pb(a)},j:Yc,G:Zc,r:$c,n:ad,s:function(){E.Ob()},a:l||B.wasmMemory,h:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return D("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return D("pthread_create called with a null thread pointer!"),28;var f=[];if(J&&0===f.length)return nd(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var u=z()[b>>
2];u+=81920;g=z()[b+8>>2];k=0!==z()[b+12>>2]}else u=2097152;(b=0==g)?g=od(16,u):(g-=u,ya(0<g));for(var n=P(228),v=0;57>v;++v)A()[(n>>2)+v]=0;z()[a>>2]=n;z()[n+12>>2]=n;a=n+152;z()[a>>2]=a;c={ya:g,Ca:u,Wa:b,lb:k,ac:c,Oa:n,Ea:d,jc:f};return J?(c.rc="spawnThread",postMessage(c,f),0):ob(c)},z:function(a,b){return cd(a,b)},w:function(a,b,c,d){return ld(a,b,c,d)},k:function(a){var b=Date.now()/1E3|0;a&&(z()[a>>2]=b);return b}};
(function(){function a(f,g){B.asm=f.exports;Ia=B.asm.J;Ka.unshift(B.asm.H);E.fb.push(B.asm.N);wa=g;if(!J){var k=E.sa.length;E.sa.forEach(function(u){E.sb(u,function(){--k||Ya("wasm-instantiate")})})}}function b(f){a(f.instance,f.module)}function c(f){return ab().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){D("failed to asynchronously prepare wasm: "+g);L(g)})}var d={a:pd};J||Xa("wasm-instantiate");if(B.instantiateWasm)try{return B.instantiateWasm(d,a)}catch(f){return D("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return va||"function"!==typeof WebAssembly.instantiateStreaming||Za()||"function"!==typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){D("wasm streaming compile failed: "+g);D("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ja);return{}})();B.___wasm_call_ctors=function(){return(B.___wasm_call_ctors=B.asm.H).apply(null,arguments)};
B._main=function(){return(B._main=B.asm.I).apply(null,arguments)};var P=B._malloc=function(){return(P=B._malloc=B.asm.K).apply(null,arguments)},lb=B._free=function(){return(lb=B._free=B.asm.L).apply(null,arguments)};B._usi_command=function(){return(B._usi_command=B.asm.M).apply(null,arguments)};B._emscripten_tls_init=function(){return(B._emscripten_tls_init=B.asm.N).apply(null,arguments)};
B._emscripten_current_thread_process_queued_calls=function(){return(B._emscripten_current_thread_process_queued_calls=B.asm.O).apply(null,arguments)};
var jb=B._emscripten_register_main_browser_thread_id=function(){return(jb=B._emscripten_register_main_browser_thread_id=B.asm.P).apply(null,arguments)},dd=B._emscripten_main_browser_thread_id=function(){return(dd=B._emscripten_main_browser_thread_id=B.asm.Q).apply(null,arguments)},db=B.__emscripten_do_dispatch_to_thread=function(){return(db=B.__emscripten_do_dispatch_to_thread=B.asm.R).apply(null,arguments)},nd=B._emscripten_sync_run_in_main_thread_4=function(){return(nd=B._emscripten_sync_run_in_main_thread_4=
B.asm.S).apply(null,arguments)},nb=B._emscripten_main_thread_process_queued_calls=function(){return(nb=B._emscripten_main_thread_process_queued_calls=B.asm.T).apply(null,arguments)},Ec=B._emscripten_run_in_main_runtime_thread_js=function(){return(Ec=B._emscripten_run_in_main_runtime_thread_js=B.asm.U).apply(null,arguments)},Jc=B.__emscripten_call_on_thread=function(){return(Jc=B.__emscripten_call_on_thread=B.asm.V).apply(null,arguments)},ib=B.__emscripten_thread_init=function(){return(ib=B.__emscripten_thread_init=
B.asm.W).apply(null,arguments)},wc=B.___errno_location=function(){return(wc=B.___errno_location=B.asm.X).apply(null,arguments)},bd=B._emscripten_get_global_libc=function(){return(bd=B._emscripten_get_global_libc=B.asm.Y).apply(null,arguments)},Q=B._pthread_self=function(){return(Q=B._pthread_self=B.asm.Z).apply(null,arguments)},kb=B.___pthread_tsd_run_dtors=function(){return(kb=B.___pthread_tsd_run_dtors=B.asm._).apply(null,arguments)},Dc=B.stackSave=function(){return(Dc=B.stackSave=B.asm.$).apply(null,
arguments)},sb=B.stackRestore=function(){return(sb=B.stackRestore=B.asm.aa).apply(null,arguments)},Ea=B.stackAlloc=function(){return(Ea=B.stackAlloc=B.asm.ba).apply(null,arguments)},rb=B._emscripten_stack_set_limits=function(){return(rb=B._emscripten_stack_set_limits=B.asm.ca).apply(null,arguments)},od=B._memalign=function(){return(od=B._memalign=B.asm.da).apply(null,arguments)},mb=B.__emscripten_allow_main_runtime_queued_calls=28240,gb=B.__emscripten_main_thread_futex=8757516;
B.ccall=function(a,b,c,d){var f={string:function(v){var p=0;if(null!==v&&void 0!==v&&0!==v){var r=(v.length<<2)+1,w=p=Ea(r);Ba(v,y(),w,r)}return p},array:function(v){var p=Ea(v.length);Fa(v,p);return p}},g=za(a),k=[];a=0;if(d)for(var u=0;u<d.length;u++){var n=f[c[u]];n?(0===a&&(a=Dc()),k[u]=n(d[u])):k[u]=d[u]}c=g.apply(null,k);c=function(v){return"string"===b?M(v):"boolean"===b?!!v:v}(c);0!==a&&sb(a);return c};B.addRunDependency=Xa;B.removeRunDependency=Ya;B.FS_createPath=lc;B.FS_createDataFile=nc;
B.FS_createPreloadedFile=qc;B.FS_createLazyFile=pc;B.FS_createDevice=N;B.FS_unlink=ec;B.PThread=E;B.PThread=E;B.wasmMemory=l;B.ExitStatus=qb;var qd;function qb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Wa=function rd(){qd||sd();qd||(Wa=rd)};
function sd(a){function b(){if(!qd&&(qd=!0,B.calledRun=!0,!xa)){Na();J||(Qb=!1,Sa(La));ha(B);if(B.onRuntimeInitialized)B.onRuntimeInitialized();if(td){var c=a,d=B._main;c=c||[];var f=c.length+1,g=Ea(4*(f+1));z()[g>>2]=Da(ma);for(var k=1;k<f;k++)z()[(g>>2)+k]=Da(c[k-1]);z()[(g>>2)+f]=0;try{var u=d(f,g);pb(u,!0)}catch(n){n instanceof qb||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),D("exception thrown: "+c),na(1,n))}finally{}}if(!J){if(B.postRun)for("function"==typeof B.postRun&&
(B.postRun=[B.postRun]);B.postRun.length;)c=B.postRun.shift(),Ma.unshift(c);Sa(Ma)}}}a=a||la;if(!(0<Ua))if(J)ha(B),Na(),postMessage({cmd:"loaded"});else{if(!J){if(B.preRun)for("function"==typeof B.preRun&&(B.preRun=[B.preRun]);B.preRun.length;)Ta();Sa(Ja)}0<Ua||(B.setStatus?(B.setStatus("Running..."),setTimeout(function(){setTimeout(function(){B.setStatus("")},1);b()},1)):b())}}B.run=sd;
function pb(a,b){if(!b||!ub()||0!==a){if(!b&&J)throw postMessage({cmd:"exitProcess",returnCode:a}),new qb(a);if(!ub()){E.Db();if(B.onExit)B.onExit(a);xa=!0}na(a,new qb(a))}}if(B.preInit)for("function"==typeof B.preInit&&(B.preInit=[B.preInit]);0<B.preInit.length;)B.preInit.pop()();var td=!0;B.noInitialRun&&(td=!1);J&&(noExitRuntime=!1,E.Pb());sd();


  return YaneuraOu.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = YaneuraOu;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return YaneuraOu; });
else if (typeof exports === 'object')
  exports["YaneuraOu"] = YaneuraOu;
